myblog/blog/urls.py
from django.urls import path
from . import views
app_name = 'blog' #超级重要
urlpatterns = [
    path('index/',views.index, name = "index_page"),
    path('article/<str:id>',views.articlePage, name = "article_page"),
    path('article/edit/<str:id>',views.article_edit_page, name='article_edit_page'),
    path('article/edit/action/',views.article_edit_page_action, name='article_edit_page_action'),
    path('article/delete/<str:id>',views.articleDelete, name='article_delete')
]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    # path('blog/', include(('blog.urls', 'blog'))),
    path('blog/', include('blog.urls')),
]

myblog/blog/models.py
from django.db import models
# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=200,default='')
    content = models.TextField(null=True)
    # 文章正文，使用的是TextField
    # 存储比较短的字符串可以使用 CharField，但对于文章的正文来说可能会是一大段文本，因此使用 TextField 来存储大段文本。
    def __str__(self) -> str:
        return self.title

myblog/blog/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse, HttpResponseRedirect
from .models import Article
# Create your views here.

#显示博客列表
def index(request):
    # return HttpResponse('this is blog!')
    all_articles  = Article.objects.all()  #这里是取所有，如果取某一个article = models.Article.objects.get(pk=1) 
    return render(request, 'index.html', {'articles':all_articles})

#显示单个博客
def articlePage(request, id):  
    article = Article.objects.get(pk = id)
    return render(request, 'article_page.html', {'article':article})


def article_edit_page(request, id):
    # str方法将参数转化为字符串，避免因传递类型差异引起的错误
    # 0代表是新增博客，否则是编辑博客，编辑博客时需要传递博客对象到页面并显示
    if str(id) =='0':
        return render(request, 'article_edit_page.html')   #既然写新博客和编辑都是跳转到同一个页面，而编辑时需要传递参数，
                                                        #而写博客不需要传递参数，为了兼容，我们都传递一个参数，写新博客时传递一个0，以做区别，
    article = Article.objects.get(pk = id)
    return render(request, 'article_edit_page.html',{'article':article})

#编辑单个博客，以及创建新的博客
def article_edit_page_action(request):
    title = request.POST.get('title','默认标题')
    content = request.POST.get('content',"默认内容")
    article_id = request.POST.get('article_id_hidden','0')##隐藏参数，参数是在web中定义  
    print("article_id =",str(article_id ))  
    ##保存数据
    ##如果是0，标记新增，使用create方法，否则使用save方法
    ##新增是返回首页，编辑是返回详情页
    if str(article_id)=='0':
        Article.objects.create(title = title, content=content) #保存数据
        ##数据保存完成，返回首页
        all_articles = Article.objects.all()
        temp = {'articles':all_articles}
        return HttpResponseRedirect(reverse('blog:index_page'),temp)
    article = Article.objects.get(pk = article_id)
    article.title = title    #完成title update
    article.content = content #完成 content update
    article.save()
    return render(request, 'article_page.html',{'article':article})

def articleDelete(request, id):
    article = Article.objects.get(pk = id)
    article.delete()
    articles = Article.objects.all()      #准备返回主页
    return HttpResponseRedirect(reverse('blog:index_page'), {'articles':articles})

myblog/blog/templates/article_edit_page.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Blog Edit</title>
</head> <!---->
<form action="{% url 'blog:article_edit_page_action' %}" method="post">   <!--这里是定义了一个form表单，用于填写博客标题、内容，并提交，在form中定义了一个action，这个是当提交按钮点击时触发的事件，暂时我们先空着。>-->
    {% csrf_token %}   <!--这个必须添加，否则访问时报403错误-->
    {% if article%}
    <input type="hidden" name="article_id_hidden"  value="{{ article.id }}"> <!--设置隐藏内容-->
        <label>Title
            <input type="text" name="title" value = {{article.title}}>
        </label>
        </br> 
        <label>Body
            <input type="text" name="content" value = {{article.content}}>
        </label>
        </br>
        <input type="submit" value="submit">
    {% else %}
        <input type ="hidden" name="article_id_hidden" value="0">
        <label>Title
            <input type="text" name="title">
        </label>
        </br> 
        <label>Body
            <input type="text" name="content">
        </label>
        </br>
        <input type="submit" value="submit">
    {% endif %}
</form>
<body>

</body>
</html>

myblog/blog/templates/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog Detail</title>
</head>
<body>
    <!--主要就是为了显示这个博客的内容-->
    <h3>title： {{ article.title }}</h3>
    </br>
    <h3>body: {{ article.content }}</h3>
    <a href="{% url 'blog:article_edit_page' 0 %}">create</a>
    <a href="{% url 'blog:article_edit_page' article.id %}">edit</a>
    <a href="{% url 'blog:article_delete' article.id %}">delete</a>
    <a href="{% url 'blog:index_page' %}">home</a>
</body>
</html>

myblog/blog/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index Page</title>
</head>
<body>
<h3>Blog list：</h3>
    {% for article in articles %}    <!--这是DTL的语法-->
        <!--<a href="../article/{{ article.id }}"> {{ article.title }} </a>   --> <!--此处先不添加跳转页面，稍后再添加-->
        <a href="{% url 'blog:article_page' article.id %}"> {{ article.title }} </a> 
        <div>
            <!-- {{article.content}} -->
        </div>
        <br/> 
    {% endfor %}    <!--for循环必须以这个结尾-->
    <a href="{% url 'blog:article_edit_page' 0 %}">Create a Blog</a>
</body>  
</html>